config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resources :sitters, only: %i[new create edit]
  end

  patch "sitters/:id", to: "sitters#update", as: :update_sitter

  get "users/:user_id/sitters", to: "sitters#my_sitters", as: "my_sitters"

  resources :sitters, only: %i[index show] do
    resources :bookings, only: %i[new create edit update show]
  end

  resources :bookings, only: %i[index]

  resources :bookings, only: :destroy
  delete '/sitters/:id', to: 'sitters#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :sitter
end

app/models/sitter.rb
class Sitter < ApplicationRecord
  belongs_to :user
  validates :start_date, :end_date, :city, presence: true
  has_one_attached :photo

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_sitter, only: %i[new create]

  def index
    @bookings = Booking.where(user: current_user) # user_id:  current_user.id
  end

  def show; end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.sitter = @sitter
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @booking.update(booking_params)
    # @booking.user = current_user
    # @booking.sitter = @sitter
    if @booking.save
      redirect_to user_booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_sitter
    @sitter = Sitter.find(params[:sitter_id])
  end

  def booking_params
    params.require(:booking).permit(:end_date, :start_date, :plants_quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

  end
end

app/controllers/sitters_controller.rb
class SittersController < ApplicationController
  before_action :set_sitter, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:city].present? && params[:start_date].present? && params[:end_date].present?
      start_date = params[:start_date]
      end_date = params[:end_date]
      @sitters = Sitter.where('start_date < ?', start_date)
      .and(Sitter.where('end_date > ?', end_date)).and(Sitter.where(city: params[:city]))
    else
      @sitters = Sitter.all
    end
  end

  def my_sitters
    @sitters = Sitter.where(user: current_user)
  end

  def show; end

  def new
    @sitter = Sitter.new
    @user = current_user
  end

  def create
    @sitter = Sitter.new(sitter_params)
    @sitter.user = current_user
    if @sitter.save
      redirect_to sitters_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    @sitter.user = current_user
    @sitter.update(sitter_params)
    if @sitter.save
      redirect_to sitter_path(@sitter)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @sitter.destroy
    redirect_to sitters_url
    # borrar las booking de este sitter
  end

  private

  def set_sitter
    @sitter = Sitter.find(params[:id])
  end

  def sitter_params
    params.require(:sitter).permit(:end_date, :start_date, :photo, :description, :city)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #  super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address phone_number sitter city photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container mt-3">
  <h1>Cuidadores agendados</h1>
  <div class="row">
    <% @bookings.each do |booking| %>
      <div class="col-4">
        <div class="card my-2">
          <% if booking.sitter.photo.attached? %>
            <%= cl_image_tag booking.sitter.photo.key, class: "card-img-top", style: "height: 200px"  %>
          <% elsif booking.sitter.user.photo.attached? %>
            <%= cl_image_tag bookinh.sitter.user.photo.key, class: "card-img-top", style: "height: 200px" %>
          <% else %>
            <%= image_tag "https://img.freepik.com/free-photo/houseplant-background-plant-lovers_53876-130004.jpg?w=740&t=st=1664330565~exp=1664331165~hmac=c24e8fdd059fac29ec263a0a17113edf37dc64b586df368fe5550a8c38ad688f", class: "card-img-top", style: "height: 200px" %>
          <% end %>
              <div class="card-body">
                <h2><%= booking.sitter.user.first_name %></h2>
                <p>Cuidará tus plantas desde <b><%= booking.start_date %></b> hasta <b><%= booking.end_date %></b></p>
                <p>Contacta a <%= booking.user.first_name %></p>
                <% if booking.sitter.user.phone_number %>
                  <p>Cel: <%= booking.sitter.user.phone_number %></p>
                <% end %>
                  <p>Correo: <%= booking.sitter.user.email %></p>
              </div>
          </div>
        </div>
      <% end %>
     </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="d-flex justify-content-center mt-3">
  <div class="col-6 justify-content-md-center bg-white p-5 mb-3 rounded">
    <div class="row">
      <div class="col-12">
        <h2>Agenda al cuidador para tus plantas</h2>
      </div>
    </div>
    <p>Recuerda que la disponibilidad del cuidador es de <b><%= @sitter.start_date %></b> a <b><%= @sitter.end_date %></b></p>
    <%= simple_form_for [@sitter, @booking] do |f| %>
      <%= f.input :start_date, label: "Fecha inicial" %>
      <%= f.input :end_date, label: "Fecha final" %>
      <%= f.input :plants_quantity, label: "¿Cuántas plantas tienes?" %>
      <%= f.button :submit, "Agenda", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-3">
  <h2>Nombre: <%= @booking.user.first_name %></h2>
  <p>Duración: <%= @booking.start_date %> - <%= @booking.end_date %></p>
  <p>Cantidad de plantas: <%= @booking.plants_quantity%> </p>
  <%= link_to "View bookings", bookings_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPlantr</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render 'shared/navbar' %>
    <%# <div class="container mt-3"> %>
      <%= yield %>
    <%# </div> %>
  </body>

  <footer>
    <%= render "shared/footer" %>
  </footer>
</html>

app/views/pages/home.html.erb
  <div id="carouselExampleDark" class="carousel carousel-white slide"
  data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner" >
      <div class="carousel-item active" data-bs-interval="10000" style="height: 300px">
        <img src="https://media.admagazine.com/photos/618a64b929327ed3de99d6bc/master/w_1600%2Cc_limit/73453.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1>¡Bienvenidos a Plantr!</h1>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="2000" style="height: 300px">
        <img src="https://decoracion2.com/imagenes/2021/08/trucos-caseros-para-el-cuidado-de-las-plantas-7.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1>Encuentra los mejores cuidadores para ti</h1>
        </div>
      </div>
      <div class="carousel-item" style="height: 300px">
        <img src="https://www.hogarmania.com/archivos/202002/principales-dudas-sobre-el-cuidado-de-los-cactus-y-las-plantas-crasas-1280x720x80xX.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1>Cerca y rápido sin muchas búsquedas</h1>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://img.freepik.com/free-photo/houseplant-background-plant-lovers_53876-130004.jpg?w=740&t=st=1664330565~exp=1664331165~hmac=c24e8fdd059fac29ec263a0a17113edf37dc64b586df368fe5550a8c38ad688f
);">
  <div class="container">
    <%= form_with url: sitters_path, method: :get, class: "d-flex" do %>
      <%= select_tag :city,
        options_for_select([["Medellín"], ["Envigado"], ["Itagüí"]]),
        class: "form-control",
        placeholder: "Looking your City"
      %>
      <%= text_field_tag :start_date,
        params[:start_date],
        class: "form-control", type: :date,
        placeholder: "start day D-M-A"
      %>
      <%= text_field_tag :end_date,
        params[:end_date],
        class: "form-control", type: :date,
        placeholder: "End day D-M-A"
      %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Plantr <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" class="text-start">
  <div class="container-fluid">
    <div class="d-flex">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/100/100662.png" %>
        <%#= image_tag("logo.jpeg") %>
      <% end %>
      <h1 class="title">Plantr</h1>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if current_user.sitter %>
            <li class="nav-item active">
              <%= link_to "Agregar disponibilidad", new_user_sitter_path(current_user), class: "nav-link text-info" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Ver cuidadores", sitters_path, class: "nav-link text-info" %>
          </li>
          <li class="nav-item dropdown">
          <% if current_user.photo.attached?  %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, style: "width:50px;height:50px;"%>
            <% else %>
            <%= image_tag "https://media.istockphoto.com/vectors/aloe-vera-in-doodle-style-cute-cartoon-plant-in-pot-colorful-vector-vector-id1354593962?k=20&m=1354593962&s=612x612&w=0&h=y4zu6MSY3yNT3cWMV1dDhAijUYJBl0uvH8YDl8fLWmU=", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.sitter %>
                <%= link_to "Perfil", user_sitters_path(current_user), class: "dropdown-item" %>
              <% end %>
              <%= link_to "Cuidadores agendados", bookings_path, class: "dropdown-item" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="btn btn-primary">
            <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/sitters/edit.html.erb
<div class="d-flex justify-content-center">
  <div class="col-6 justify-content-md-center bg-white p-5 mb-3 rounded">
    <div class="row">
      <div class="col-12">
        <h2>Add availability as a sitter</h2>
      </div>
    </div>

    <%= simple_form_for [@user, @sitter] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <%= button_to "Update", update_sitter_path(current_user, @sitter), :method => :patch %>
      <%# <%= f.button :submit, "Edit sitter", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/sitters/index.html.erb
<div class="container my-1">
  <div class="container">
        <%= form_with url: sitters_path, method: :get, class: "d-flex" do %>
      <%= select_tag :city,
        options_for_select([["Medellín"], ["Envigado"], ["Itagüí"]]),
        class: "form-control",
        placeholder: "Looking your City"
      %>
      <%= text_field_tag :start_date,
        params[:start_date],
        class: "form-control", type: :date,
        placeholder: "start day D-M-A"
      %>
      <%= text_field_tag :end_date,
        params[:end_date],
        class: "form-control", type: :date,
        placeholder: "End day D-M-A"
      %>

      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
  <% if @sitters.empty? %>
    <h2>Sin resultados</h2>
  <% else %>
    <div class="row gy-3 mt-3">
      <% @sitters.each do |sitter| %>
        <div class="col-4">
          <div class="card h-100">
            <% if sitter.photo.attached? %>
              <%= cl_image_tag sitter.photo.key, class: "card-img-top", style: "height: 200px"  %>
            <% elsif sitter.user.photo.attached? %>
              <%= cl_image_tag sitter.user.photo.key, class: "card-img-top", style: "height: 200px" %>
            <% else %>
              <%= image_tag "https://img.freepik.com/free-photo/houseplant-background-plant-lovers_53876-130004.jpg?w=740&t=st=1664330565~exp=1664331165~hmac=c24e8fdd059fac29ec263a0a17113edf37dc64b586df368fe5550a8c38ad688f", class: "card-img-top", style: "height: 200px" %>
            <% end %>
            <div class="card-body">
              <h2> <%= sitter.user.first_name %></h2>
              <h4><%= sitter.city %></h4>
              <p>Disponibilidad desde <b><%= sitter.start_date %></b> hasta <b><%= sitter.end_date %></b></p>
              <%= link_to "View details", sitter_path(sitter), class:  "btn btn-success mx-3" %>
              <%= link_to "Book sitter", new_sitter_booking_path(sitter), class: "btn btn-success mx-3" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/sitters/my_sitters.html.erb
<div class="container mt-3">
  <h2>Mis disponibilidades como cuidador</h2>
  <div class="row">
    <% @sitters.each do |sitter| %>
      <div class="col-4">
        <div class="card my-2">
              <% if sitter.photo.attached? %>
                <%= cl_image_tag sitter.photo.key, class: "card-img-top", style: "height: 200px"  %>
              <% elsif sitter.user.photo.attached? %>
                <%= cl_image_tag sitter.user.photo.key, class: "card-img-top", style: "height: 200px" %>
              <% else %>
                <%= image_tag "https://img.freepik.com/free-photo/houseplant-background-plant-lovers_53876-130004.jpg?w=740&t=st=1664330565~exp=1664331165~hmac=c24e8fdd059fac29ec263a0a17113edf37dc64b586df368fe5550a8c38ad688f", class: "card-img-top", style: "height: 200px" %>
              <% end %>
              <div class="card-body">
                <h2><%= sitter.user.first_name %></h2>
                <p>Disponibilidad desde: <b><%= sitter.start_date %></b> - hasta: <b><%= sitter.end_date %></b></p>
                  <%= link_to "Ver detalle", sitter_path(sitter), class:  "btn btn-success me-2" %>
                  <% if sitter.user == current_user %>
                    <%= link_to "Editar", edit_user_sitter_path(current_user, sitter), class:  "btn btn-success me-2" %>
                    <%= link_to "Eliminar",
                     sitter_path(sitter), class:  "btn btn-success me-2",
                     data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
                    %>
                <% end %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/sitters/new.html.erb
<div class="d-flex justify-content-center mt-3">
  <div class="col-6 justify-content-md-center bg-white p-5 mb-3 rounded">
    <div class="row">
      <div class="col-12">
        <h2>Agrega tu disponibilidad como cuidador</h2>
      </div>
    </div>

    <%= simple_form_for [@user, @sitter] do |f| %>
      <%= f.input :start_date, label: "Fecha inicial" %>
      <%= f.input :end_date, label: "Fecha final" %>
      <%= f.input :city, label: "Ciudad", collection: %w[Medellín Envigado Itagüí] %>
      <%= f.input :description, label: "Descripción" %>
      <%= f.input :photo, as: :file, label: "Imagen" %>
      <%= f.button :submit, "Agregar disponibilidad", class: "btn btn-primary mb-3" %>
    <% end %>
  </div>
</div>

app/views/sitters/show.html.erb
<div class="container mt-3">
  <div class="row mb-3">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <div class="d-flex">
            <% if @sitter.photo.attached? %>
              <%= cl_image_tag @sitter.photo.key, style:"height:300px;width:300px" %>
            <% elsif @sitter.user.photo.attached? %>
              <%= cl_image_tag @sitter.user.photo.key, style:"height:300px;width:300px" %>
            <% else %>
              <%= image_tag "https://media.istockphoto.com/vectors/aloe-vera-in-doodle-style-cute-cartoon-plant-in-pot-colorful-vector-vector-id1354593962?k=20&m=1354593962&s=612x612&w=0&h=y4zu6MSY3yNT3cWMV1dDhAijUYJBl0uvH8YDl8fLWmU=", style:"height: 300px;width:300px;" %>
            <% end %>
            <div class="content ms-3">
              <h2><%= @sitter.user.first_name%> <%= @sitter.user.last_name%></h2>
              <h3><%= @sitter.city %></h3>
              <p><%= @sitter.description %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card">
        <div class="card-header bg-secondary text-white">
          <h3>Puedo cuidar tus plantas entre</h3>
        </div>
        <div class="card-body">
          <h3><b><%= @sitter.start_date %></b> y</h3>
          <h3><b><%= @sitter.end_date %></b></h3>
          <%= link_to "Agéndame", new_sitter_booking_path(@sitter), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <% if Sitter.where(user: @sitter.user).count > 1 %>
  <hr>
    <h2>Este cuidador también está disponible en estas fechas</h2>
     <% Sitter.where(user: @sitter.user).each do |sitter| %>
        <% unless sitter == @sitter %>
          <ul>
            <li><h4>Disponibilidad <%= sitter.start_date %> - <%= sitter.end_date %> <%= link_to "Ver detalle", sitter_path(sitter), class: "btn btn-primary" %>
            <%= link_to "Agendar", new_sitter_booking_path(sitter), class: "btn btn-primary" %></h4>
            </li>
          </ul>
        <% end %>
      <% end %>
  <% end %>
</div>